[package]
name = "yu-practice-game"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = { version = "0.19", features = ["crossterm"] }
crossterm = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
lazy_static = "1.4"
rand = "0.8"
chrono = "0.4"
